version: '3.11'

services:
  fast:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: unless-stopped
